/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ArchRouteImport } from './routes/arch'

const ArchRoute = ArchRouteImport.update({
  id: '/arch',
  path: '/arch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/arch': typeof ArchRoute
}
export interface FileRoutesByTo {
  '/arch': typeof ArchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/arch': typeof ArchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/arch'
  fileRoutesByTo: FileRoutesByTo
  to: '/arch'
  id: '__root__' | '/arch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ArchRoute: typeof ArchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/arch': {
      id: '/arch'
      path: '/arch'
      fullPath: '/arch'
      preLoaderRoute: typeof ArchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ArchRoute: ArchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
